client/urls.py
from django.urls import path
from client import views

urlpatterns = [
    path('myspace/user/settings/', views.userSettings, name='user-settings'),
    path('myspace/user/profile/', views.UserProfile.as_view(), name='user-profile'),
    path('myspace/customers/', views.CustomerListView.as_view(), name='customer-list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from django.conf import settings
from django.conf.urls.static import static
from config import views


urlpatterns = [
    path('superadmin_010123/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('myspace/', views.MySpaceViews.as_view(), name='dashboard'),
    path('', include('frontend.urls')),
    path('', include('client.urls')),
    



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'config.views.page_not_found_view'
handler500 = 'config.views.error_view'
handler403 = 'config.views.permission_denied_view'
handler400 = 'config.views.bad_request_view'

admin.site.site_header = "SuperAdmin projectX"
admin.site.site_title = "ProjectX"
admin.site.index_title = "Admin"

client/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserInfo(models.Model):

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, unique=True, related_name='profile')
    company_name = models.CharField(_("Company or project Name"), max_length=200)
    company_vat = models.CharField(_("Company VAT"), max_length=200, blank=True, null=True)
    whatsapp = models.CharField(_("WhatsApp"), max_length=200)
    domaine = models.URLField(_("Domain"), max_length=200, blank=True, null=True)
    validated_client = models.BooleanField(default=False)
    accepted_terms = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Personal info"
        verbose_name_plural = "Personal info"

    def __str__(self):
        return self.company_name


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, *args, **kwargs):
    if created:
        UserInfo.objects.create(user=instance)
    instance.profile.save()

frontend/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.urls import reverse
from ckeditor.fields import RichTextField


class Contact(models.Model):
    full_name = models.CharField(_('Full Name'), max_length=100)
    email = models.EmailField(_('Email'), max_length=200)
    topics = models.CharField(_('Topics'), max_length=250)
    message = models.TextField(_('Message'))

    def __str__(self):
        return self.full_name


class Category(models.Model):
    name = models.CharField(_('Name'), max_length=100)
    slug = AutoSlugField(populate_from="name", unique=True)
    feature_image = models.ImageField(
        blank=True, null=True, upload_to='frontend/blog/categories/%Y/%m/%d/', default='default-thumb.png')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Blog (models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    feature_image = ImageField(_('Feature Image'), blank=True, null=True,
                               upload_to='frontend/blog/articles/%Y/%m/%d/', default='default-thumb.png')
    title = models.CharField(_('Title'), max_length=300)
    slug = AutoSlugField(populate_from="title", unique_with='published__month')
    published = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, related_name='category')
    content = RichTextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"slug": self.slug})


class Page(models.Model):
    title = models.CharField(_('Title'), max_length=300)
    slug = AutoSlugField(populate_from="title", unique=True)
    content = RichTextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'

client/forms.py
from django import forms
from allauth.account.forms import LoginForm, SignupForm, ResetPasswordForm, ChangePasswordForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from client.models import UserInfo
from django.contrib.auth.forms import UserChangeForm


class CustomLoginForm(LoginForm):

    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['password'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})


class CustomSignupForm(SignupForm):

    def __init__(self, *args, **kwargs):
        super(CustomSignupForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder': _(
            'username'), 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['email'].widget.attrs.update({'placeholder': _(
            'email'), 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['password1'].widget.attrs.update({'placeholder': _(
            'password'), 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['password2'].widget.attrs.update({'placeholder': _(
            'password again'), 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})

    def save(self, request):

        user = super(CustomSignupForm, self).save(request)
        return user


class CustomResetPasswordForm(ResetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(CustomResetPasswordForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'placeholder': _(
            'email'), 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})


class CustomPasswordChangeForm(ChangePasswordForm):

    def __init__(self, *args, **kwargs):
        user = super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['oldpassword'].widget.attrs.update({'placeholder': _(
            'Old password'), 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 my-4'})
        self.fields['password1'].widget.attrs.update({'placeholder': _(
            'New password'), 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 my-4'})
        self.fields['password2'].widget.attrs.update({'placeholder': _(
            'New password confirmation'), 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 my-4'})

        return user


class PasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'placeholder': _(
            'Old password'), 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 my-4'})
        self.fields['new_password1'].widget.attrs.update({'placeholder': _(
            'New password'), 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 my-4'})
        self.fields['new_password2'].widget.attrs.update({'placeholder': _(
            'New password confirmation'), 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 my-4'})


class UserInfoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserInfoForm, self).__init__(*args, **kwargs)

        self.fields['company_name'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['domaine'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', })
        self.fields['validated_client'].widget.attrs.update(
            {'class':  'font-medium text-gray-900 dark:text-gray-300', })
        
        self.fields['company_vat'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', })
        
        self.fields['whatsapp'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', })

        self.fields['validated_client'].widget.attrs.update({
            'class': 'w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600'
        })
        self.fields['accepted_terms'].widget.attrs.update({
            'class': 'w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600'
        })
    class Meta:
        model = UserInfo
        exclude = ['user']
        fields = '__all__'


class UserForm(UserChangeForm):
    password = None

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['last_name'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', })
        self.fields['email'].widget.attrs.update(
            {'class':  'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', })

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

client/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView, DeleteView
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from client.forms import UserForm, UserInfoForm


@login_required
def userSettings(request):
    template_name = 'client/settings.html'
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        info_form = UserInfoForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and info_form.is_valid():
            user_form.save()
            info_form.save()
            messages.success(request, _(
                "Your information has been successfully updated"))
            # TODO: add notofication on update user info
            # sender = request.user
            # recipient = User.objects.filter(is_superuser=True)
            # message = _('New cusomer account is waiting for confirmation')
            # notify.send(sender=sender, recipient=recipient, verb='Message',
            # description='New cusomer account is waiting for confirmation', level='light')
            return redirect('dashboard')
    else:
        user_form = UserForm()
        info_form = UserInfoForm()
    if request.method == 'GET':
        user_form = UserForm(instance=request.user)
        info_form = UserInfoForm(instance=request.user.profile)
    context = {
        'user_form': user_form,
        'info_form': info_form
    }
    return render(request, template_name, context)


class UserProfile(TemplateView):
    template_name = 'client/profile.html'


class CustomerListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    template_name = 'client/admin/list.html'
    model = User


class CustomerDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = User
    success_message = _('Customer has been successfully deleted')

client/templates/client/settings.html
{% extends 'base/base.html' %}
{% load static i18n %}
{% block title %}{% translate "Profile" %}{% endblock title %}
{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    <hr class="mb-6 mx-4 w-70 h-1 bg-gray-300 rounded border-0 md:my-10 dark:bg-gray-300">

    <div class="grid col-1 mx-auto max-w-7xl gap-6 mb-6 md:grid-cols-1 lg:grid-cols-2 md:mt-10">

        <div class="justify-center p-2 md:p-4">
            <label for="id_first_name" class="block mb-2 text-lg font-medium text-gray-900 dark:text-gray-300">
                {{user_form.first_name.label}}
            </label>
            {{user_form.first_name}}
            {% for error in user_form.first_name.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
        <div class="order-2 lg:order-3 justify-center p-2 md:p-4">
            <label for="id_last_name" class="block mb-2 text-lg font-medium text-gray-900 dark:text-gray-300">
                {% translate "Last Name: " %}
            </label>
            <div class="mx-auto text-gray-800 dark:text-gray-300  ">{{user_form.last_name}}</div>
            {% for error in user_form.last_name.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
        <div class="order-2 lg:order-3 justify-center p-2 md:p-4">
            <label for="id_email" class="block mb-2 text-lg font-medium text-gray-900 dark:text-gray-300">
                {% translate "Email address: " %}
            </label>
            <div class="mx-auto text-gray-800 dark:text-gray-300  ">{{user_form.email}}</div>
            {% for error in user_form.email.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
        <div class="order-2 lg:order-3 justify-center p-2 md:p-4">
            <label for="id_company_name" class="block mb-2 text-lg font-medium text-gray-900 dark:text-gray-300">
                {% translate "Company Name: " %}
            </label>
            <div class="mx-auto text-gray-800 dark:text-gray-300  ">{{info_form.company_name}}</div>
            {% for error in info_form.company_name.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
        <div class="order-2 lg:order-3 justify-center p-2 md:p-4">
            <label for="id_domaine" class="block mb-2 text-lg font-medium text-gray-900 dark:text-gray-300">
                {% translate "Domain: " %}
            </label>
            <div class="mx-auto text-gray-800 dark:text-gray-300  ">{{info_form.domaine}}</div>
            {% for error in info_form.domaine.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
        <div class="order-2 lg:order-3 justify-center p-2 md:p-4">
            <label for="id_company_vat" class="block mb-2 text-lg font-medium text-gray-900 dark:text-gray-300">
                {% translate "VAT: " %}
            </label>
            <div class="mx-auto text-gray-800 dark:text-gray-300  ">{{info_form.company_vat}}</div>
            {% for error in info_form.company_vat.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
        <div class="order-2 lg:order-3 justify-center p-2 md:p-4">
            <label for="id_whatsapp" class="block mb-2 text-lg font-medium text-gray-900 dark:text-gray-300">
                {% translate "WhatsApp: " %}
            </label>
            <div class="mx-auto text-gray-800 dark:text-gray-300  ">{{info_form.whatsapp}}</div>
            {% for error in info_form.whatsapp.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
        <div class="hidden order-2 lg:order-3 justify-center p-2 md:p-4">
            
            <div class="mx-auto text-gray-800 dark:text-gray-300  ">{{info_form.validated_client}}</div>
            {% for error in info_form.validated_client.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
        <div class="hidden order-2 lg:order-3 justify-center p-2 md:p-4">
            
            <div class="mx-auto text-gray-800 dark:text-gray-300  ">{{info_form.accepted_terms}}</div>
            {% for error in info_form.accepted_terms.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
    </div>
    <div class="mx-auto max-w-7xl">
        <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">

            {% if object %}
            {% translate "Update" %}
            {% else %}
            {% translate "Publish" %}
            {% endif %}

            <svg aria-hidden="true" class="ml-2 -mr-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                    clip-rule="evenodd"></path>
            </svg>
        </button>
    </div>

</form>
{% endblock content %}