client/urls.py
from django.urls import path
from client import views

urlpatterns = [
    path('myspace/user/settings/', views.userSettings, name='user-settings'),
    path('myspace/user/profile/', views.UserProfile.as_view(), name='user-profile'),
    path('myspace/customers/', views.CustomerListView.as_view(), name='customer-list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from django.conf import settings
from django.conf.urls.static import static
from config import views


urlpatterns = [
    path('superadmin_010123/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('myspace/', views.MySpaceViews.as_view(), name='dashboard'),
    path('', include('frontend.urls')),
    path('', include('client.urls')),
    



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'config.views.page_not_found_view'
handler500 = 'config.views.error_view'
handler403 = 'config.views.permission_denied_view'
handler400 = 'config.views.bad_request_view'

admin.site.site_header = "SuperAdmin projectX"
admin.site.site_title = "ProjectX"
admin.site.index_title = "Admin"

frontend/urls.py
from django.urls import path
from frontend import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('services/design/', views.DesignView.as_view(), name='design'),
    path('services/web-development/', views.WebView.as_view(), name='web'),
    path('services/mobile-development/', views.MobileView.as_view(), name='mobile'),
    path('services/seo/', views.SeoView.as_view(), name='seo'),
    path('services/marketing/', views.MarketingView.as_view(), name='marketing'),
    path('contact/', views.ContactView.as_view(), name='contact'),

    # Extra Pages
    path('myspace/pages/add/', views.AddPageView.as_view(), name='page-add'),
    path('myspace/pages/update/<slug>/', views.UpdatePageView.as_view(), name='page-update'),
    path('myspace/pages/delete/<slug>/', views.DeletePageView.as_view(), name='page-delete'),
    path('myspace/pages/list/', views.ListPageView.as_view(), name='page-list'),
    path('<slug>/', views.DetailPageView.as_view(), name='page-detail'),

    # Dev Tips(Blog and categories)
    path('dev-tips/', views.BlogView.as_view(), name='articles'),
    path('dev-tips/<slug>/', views.DetailsBlogView.as_view(), name='post-detail'),
    path('myspace/blog/add/', views.AddPostView.as_view(), name='post-add'),
    path('myspace/blog/update/<slug>/', views.UpdatePostView.as_view(), name='post-update'),
    path('myspace/blog/delete/<slug>/', views.DeletePostView.as_view(), name='post-delete'),
    path('myspace/blog/list/', views.ListPostAdminView.as_view(), name='post-admin-list'),

    path('myspace/blog/category/add/', views.AddCategoryView.as_view(), name='category-add'),
    path('myspace/blog/category/update/<slug>/', views.UpdateCategoryView.as_view(), name='category-update'),
    path('myspace/blog/category/delete/<slug>/', views.DeleteCategoryView.as_view(), name='category-delete'),
]

frontend/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.urls import reverse
from ckeditor.fields import RichTextField


class Contact(models.Model):
    full_name = models.CharField(_('Full Name'), max_length=100)
    email = models.EmailField(_('Email'), max_length=200)
    topics = models.CharField(_('Topics'), max_length=250)
    message = models.TextField(_('Message'))

    def __str__(self):
        return self.full_name


class Category(models.Model):
    name = models.CharField(_('Name'), max_length=100)
    slug = AutoSlugField(populate_from="name", unique=True)
    feature_image = models.ImageField(
        blank=True, null=True, upload_to='frontend/blog/categories/%Y/%m/%d/', default='default-thumb.png')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Blog (models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    feature_image = ImageField(_('Feature Image'), blank=True, null=True,
                               upload_to='frontend/blog/articles/%Y/%m/%d/', default='default-thumb.png')
    title = models.CharField(_('Title'), max_length=300)
    slug = AutoSlugField(populate_from="title", unique_with='published__month')
    published = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, related_name='category')
    content = RichTextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"slug": self.slug})


class Page(models.Model):
    title = models.CharField(_('Title'), max_length=300)
    slug = AutoSlugField(populate_from="title", unique=True)
    content = RichTextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'

frontend/forms.py
from django import forms
from frontend.models import Contact, Category, Blog, Page


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].widget.attrs.update(
            {'class': 'form-control mb-30'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-30'})
        self.fields['topics'].widget.attrs.update(
            {'class': 'form-control mb-30'})
        self.fields['message'].widget.attrs.update(
            {'class': 'form-control mb-30'})


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'
        exclude = ['author']
        widgets = {
            "category": forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['feature_image'].widget.attrs.update({'class': 'hidden'})
        self.fields['content'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['category'].widget.attrs.update(
            {'class': 'font-medium text-gray-900 dark:text-gray-300', })


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['feature_image'].widget.attrs.update({'class': 'hidden'})


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PageForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['content'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})

frontend/views.py
from django.shortcuts import render, redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView, DeleteView
from django.utils.translation import gettext_lazy as _
from django.core.mail import EmailMultiAlternatives
from django.contrib import messages

from frontend.models import Contact, Category, Blog, Page
from frontend.forms import ContactForm, ArticleForm, CategoryForm, PageForm


class HomeView(TemplateView):
    template_name = 'frontend/views/home.html'
    # def get_context_data(self, **kwargs):
    #     context = super(HomeView, self).get_context_data(**kwargs)
    #     context['articles'] = Blog.objects.order_by('-published')[:3]
    #     return context


class ContactView(SuccessMessageMixin, CreateView):
    model = Contact
    form_class = ContactForm
    success_message = _(
        "Your submission was successfully received, and our team will answer you as soon as possible")
    success_url = reverse_lazy("contact")
    template_name = 'frontend/views/contact.html'

    def form_valid(self, form, **kwargs):
        full_name = form.cleaned_data['full_name']
        email = form.cleaned_data['email']
        topic = form.cleaned_data['topics']
        message = form.cleaned_data['message']
        subject, from_email, to = topic, 'noreply@gisysco.com', "support@gisysco.com"
        text_content = _('New email from contact help.')
        html_content = _(
            f'Hello Team <br> <p>Mr/Ms: <strong>{full_name}</strong> need help about <strong> {topic} </strong> <br> His/Her message:<br> {message} </p> <p><a href="mailto:{email}">Reply to customer email</a></p>')
        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()
        return super().form_valid(form)

        # TODO: add notofication to the admin space  when have new contact


class DesignView(TemplateView):
    template_name = 'frontend/views/services/design.html'


class WebView(TemplateView):
    template_name = 'frontend/views/services/web_dev.html'


class MobileView(TemplateView):
    template_name = 'frontend/views/services/mobile_dev.html'


class SeoView(TemplateView):
    template_name = 'frontend/views/services/seo.html'


class MarketingView(TemplateView):
    template_name = 'frontend/views/services/marketing.html'


# Dev Tips View

class AddPostView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Blog
    template_name = 'frontend/views/blog/admin/index.html'
    success_message = _('Your post has been successfully added')
    form_class = ArticleForm
    success_url = reverse_lazy('post-admin-list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdatePostView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Blog
    form_class = ArticleForm
    template_name = 'frontend/views/blog/admin/index.html'
    success_message = _('Your post has been successfully update')
    success_url = reverse_lazy('post-admin-listt')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class DeletePostView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Blog
    template_name = 'frontend/views/blog/admin/delete.html'
    success_url = reverse_lazy('post-admin-list')
    success_message = _('Your post has been successfully deleted')


class ListPostAdminView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    model = Blog
    template_name = 'frontend/views/blog/admin/list.html'
    paginate_by = 5


class BlogView(ListView):
    model = Blog
    paginate_by = 10
    template_name = 'frontend/views/blog/blog.html'

    def get_context_data(self, **kwargs):
        kwargs['cat_list'] = Category.objects.order_by('id')
        kwargs['articles_list'] = Blog.objects.order_by('-published')[:6]

        return super(BlogView, self).get_context_data(**kwargs)


class DetailsBlogView(DetailView):
    model = Blog
    template_name = 'frontend/views/blog/details.html'

    def get_context_data(self, **kwargs):
        kwargs['cat_list'] = Category.objects.order_by('id')
        kwargs['articles_list'] = Blog.objects.order_by('-published')[:6]

        return super(DetailsBlogView, self).get_context_data(**kwargs)


class AddCategoryView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Category
    template_name = 'frontend/views/blog/admin/categories/index.html'
    success_message = _('Your category has been successfully added')
    form_class = CategoryForm
    success_url = reverse_lazy('category-add')

    def get_context_data(self, **kwargs):
        kwargs['cat_list'] = Category.objects.order_by('id')
        return super(AddCategoryView, self).get_context_data(**kwargs)


class UpdateCategoryView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Category
    template_name = 'frontend/views/blog/admin/categories/index.html'
    success_message = _('Your category has been successfully update')
    form_class = CategoryForm
    success_url = reverse_lazy('category-add')

    def get_context_data(self, **kwargs):
        kwargs['cat_list'] = Category.objects.order_by('id')
        return super(UpdateCategoryView, self).get_context_data(**kwargs)


class DeleteCategoryView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Category
    template_name = 'frontend/views/blog/admin/categories/delete.html'
    success_message = _('Your category has been successfully deleted')
    success_url = reverse_lazy('category-add')


class AddPageView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Page
    template_name = 'frontend/views/pages/admin/index.html'
    success_message = _('This page has been successfully added')
    form_class = PageForm
    success_url = reverse_lazy('page-list')


class UpdatePageView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Page
    template_name = 'frontend/views/pages/admin/index.html'
    success_message = _('This page has been successfully update')
    form_class = PageForm
    success_url = reverse_lazy('page-list')


class DeletePageView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Page
    template_name = 'frontend/views/pages/admin/delete.html'
    success_url = reverse_lazy('page-list')
    success_message = _('Your page has been successfully deleted')

    def delete(self, request, *args, **kwargs):
        messages.warning(self.request, self.success_message)
        return super(DeletePageView, self).delete(request, *args, **kwargs)


class ListPageView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    model = Page
    template_name = 'frontend/views/pages/admin/list.html'
    paginate_by = 5


class DetailPageView(SuccessMessageMixin, DetailView):
    model = Page
    template_name = 'frontend/views/pages/details.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

frontend/templates/frontend/views/blog/admin/index.html
{% extends 'base/base.html' %}
{% load static i18n %}
{% block title %}
{% if object %}
{% translate "Add post" %}
{% else %}
{% translate "Update post" %}
{% endif %}

{% endblock title %}
{% block content %}
{{form.media}}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="grid col-1 mx-auto max-w-7xl gap-6 mb-6 md:grid-cols-1 lg:grid-cols-2 md:mt-10">
        <div class="justify-center p-2 md:p-4">
            <label for="id_title" class="block mb-2 text-lg font-medium text-gray-900 dark:text-gray-300">
                {{form.title.label}}
            </label>
            {{form.title}}
            {% for error in form.title.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
        <div class="order-3 lg:order-2 justify-center p-2 md:p-4">
            <label for="id_category" class="block mb-2 text-lg font-medium text-gray-900 dark:text-gray-300">
                {{form.category.label}}
            </label>
            {{form.category}}
            {% for error in form.category.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
        <div class="order-2 lg:order-3 justify-center p-2 md:p-4">
            <label for="id_content" class="block mb-2 text-lg font-medium text-gray-900 dark:text-gray-300">
                {% translate "Article" %}
            </label>
            <div class="mx-auto text-gray-800 dark:text-gray-300  ">{{form.content}}</div>
            {% for error in form.content.errors %}
            <p><small class="text-sm text-red-700 dark:text-red-500">{{ error }}</small></p>
            {% endfor %}
        </div>
        <div class="order-4 lg:order-4 justify-center p-2 md:p-4 max-w-md">
            <label for="id_feature_image" class="block mb-2 text-lg font-medium text-gray-900 dark:text-gray-300">
                {{form.feature_image.label}}
            </label>
            <label for="id_feature_image"
                class="flex flex-col justify-center items-center w-full h-64 bg-gray-50 rounded-lg border-2 border-gray-300 border-dashed cursor-pointer dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
                <div class="flex flex-col justify-center items-center pt-5 pb-6">
                    <svg aria-hidden="true" class="mb-3 w-10 h-10 text-gray-400" fill="none" stroke="currentColor"
                        viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12">
                        </path>
                    </svg>
                    <p class="mb-2 text-lg text-gray-500 dark:text-gray-400">
                        <span class="font-semibold">{% translate "Click to upload" %}</span>
                    </p>
                    <p class="text-xs text-gray-500 dark:text-gray-400">
                        SVG, PNG, JPG or GIF (MAX. 800x400px)
                    </p>
                </div>
                {{form.feature_image}}
            </label>

        </div>
    </div>
    <div class="mx-auto max-w-7xl">
        <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">

            {% if object %}
            {% translate "Update" %}
            {% else %}
            {% translate "Publish" %}
            {% endif %}
            <svg aria-hidden="true" class="ml-2 -mr-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                    clip-rule="evenodd"></path>
            </svg>
        </button>
    </div>

</form>

{% endblock content %}

frontend/templates/frontend/views/blog/admin/list.html
{% extends 'base/base.html' %}
{% load static i18n %}
{% block title %}
{% translate "All articles" %}
{% endblock title %}

{% block content %}

<div class="mb-20 mx-auto max-w-7xl">
    <a href="{% url 'post-add' %}"
        class="text-white  bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-800 dark:hover:bg-blue-900 dark:focus:ring-gray-700 dark:border-gray-700">
        {% translate "Add new post" %}</a>
</div>


<ul class="mx-auto max-w-7xl divide-y divide-gray-200 dark:divide-gray-700">

    {% for post in object_list %}



    <li class="py-3 sm:py-4">
        <div class="flex items-center space-x-4">
            <div class="flex-shrink-0">
                <img class="w-10 h-10" src="{{post.feature_image.url}}" alt="{{post.title}}">
            </div>
            <div class="flex-1 min-w-0">
                <p class="text-sm md:text-lg font-medium text-gray-900 truncate dark:text-white">
                    {{post.title}}
                </p>
                <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                    by: {{post.author}} | {{post.published|date:"Y M d"}}
                </p>
                <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                    {% for cat in post.Category.all %} {{cat}}, {% endfor %}
                </p>
            </div>
            <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                <a href="{% url 'update-post' post.slug %}"
                    class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-xs p-2.5 text-center inline-flex items-center mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z">
                        </path>
                    </svg>
                    <span class="sr-only">{% translate "Edit" %}</span>
                </a>
                <a href="#" data-modal-toggle="popup-modal-{{post.id}}"
                    class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm p-2.5 text-center inline-flex items-center mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16">
                        </path>
                    </svg>
                    <span class="sr-only">{% translate "Delete" %}</span>
                </a>
            </div>
        </div>
    </li>
    <div id="popup-modal-{{post.id}}" tabindex="-1"
        class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 md:inset-0 h-modal md:h-full">
        <div class="relative p-4 w-full max-w-md h-full md:h-auto">
            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                <button type="button"
                    class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white"
                    data-modal-toggle="popup-modal-{{post.id}}">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd"></path>
                    </svg>
                    <span class="sr-only">{% translate "Close modal" %}</span>
                </button>
                <div class="p-6 text-center">
                    <svg aria-hidden="true" class="mx-auto mb-4 w-14 h-14 text-gray-400 dark:text-gray-200" fill="none"
                        stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>
                    <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">
                        {% translate "Are you sure you want to delete" %} <br />
                        <strong>{{post.Title}}</strong>?
                    </h3>
                    <form method="POST" action="{% url 'delete-post' post.slug %}">
                        {% csrf_token %}
                        <button data-modal-toggle="popup-modal-{{post.id}}" type="submit"
                            class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center mr-2">
                            {% translate "Yes, I'm sure" %}
                        </button>
                        <button data-modal-toggle="popup-modal-{{post.id}}" type="button"
                            class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">
                            {% translate "No, cancel" %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <div id="alert-border-1" class="flex p-4 bg-blue-100 border-t-4 border-blue-500 dark:bg-blue-200" role="alert">
        <svg class="flex-shrink-0 w-5 h-5 text-blue-700" fill="currentColor" viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                clip-rule="evenodd"></path>
        </svg>
        <div class="ml-3 text-sm font-medium text-blue-700">
            {% translate "Sorry, there are no articles in the list." %}
        </div>
        <button type="button"
            class="ml-auto -mx-1.5 -my-1.5 bg-blue-100 dark:bg-blue-200 text-blue-500 rounded-lg focus:ring-2 focus:ring-blue-400 p-1.5 hover:bg-blue-200 dark:hover:bg-blue-300 inline-flex h-8 w-8"
            data-dismiss-target="#alert-border-1" aria-label="Close">
            <span class="sr-only">{% translate "Dismiss" %}</span>
            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                    clip-rule="evenodd"></path>
            </svg>
        </button>
    </div>
    {% endfor %}
</ul>


{% endblock content %}