client/urls.py
from django.urls import path
from client import views

urlpatterns = [
    path('myspace/user/settings/', views.userSettings, name='user-settings'),
    path('myspace/user/profile/', views.UserProfile.as_view(), name='user-profile'),
    path('myspace/customers/', views.CustomerListView.as_view(), name='customer-list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from django.conf import settings
from django.conf.urls.static import static
from config import views


urlpatterns = [
    path('superadmin_010123/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('myspace/', views.MySpaceViews.as_view(), name='dashboard'),
    path('', include('frontend.urls')),
    path('', include('client.urls')),
    



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'config.views.page_not_found_view'
handler500 = 'config.views.error_view'
handler403 = 'config.views.permission_denied_view'
handler400 = 'config.views.bad_request_view'

admin.site.site_header = "SuperAdmin projectX"
admin.site.site_title = "ProjectX"
admin.site.index_title = "Admin"

frontend/urls.py
from django.urls import path
from frontend import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('services/design/', views.DesignView.as_view(), name='design'),
    path('services/web-development/', views.WebView.as_view(), name='web'),
    path('services/mobile-development/', views.MobileView.as_view(), name='mobile'),
    path('services/seo/', views.SeoView.as_view(), name='seo'),
    path('services/marketing/', views.MarketingView.as_view(), name='marketing'),
    path('contact/', views.ContactView.as_view(), name='contact'),

    # Extra Pages
    path('myspace/pages/add/', views.AddPageView.as_view(), name='page-add'),
    path('myspace/pages/update/<slug>/', views.UpdatePageView.as_view(), name='page-update'),
    path('myspace/pages/delete/<slug>/', views.DeletePageView.as_view(), name='page-delete'),
    path('myspace/pages/list/', views.ListPageView.as_view(), name='page-list'),
    path('<slug>/', views.DetailPageView.as_view(), name='page-detail'),

    # Dev Tips(Blog and categories)
    path('dev-tips/', views.BlogView.as_view(), name='articles'),
    path('dev-tips/<slug>/', views.DetailsBlogView.as_view(), name='post-detail'),
    path('myspace/blog/add/', views.AddPostView.as_view(), name='post-add'),
    path('myspace/blog/update/<slug>/', views.UpdatePostView.as_view(), name='post-update'),
    path('myspace/blog/delete/<slug>/', views.DeletePostView.as_view(), name='post-delete'),
    path('myspace/blog/list/', views.ListPostAdminView.as_view(), name='post-admin-list'),

    path('myspace/blog/category/add/', views.AddCategoryView.as_view(), name='category-add'),
    path('myspace/blog/category/update/<slug>/', views.UpdateCategoryView.as_view(), name='category-update'),
    path('myspace/blog/category/delete/<slug>/', views.DeleteCategoryView.as_view(), name='category-delete'),
]

frontend/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.urls import reverse
from ckeditor.fields import RichTextField


class Contact(models.Model):
    full_name = models.CharField(_('Full Name'), max_length=100)
    email = models.EmailField(_('Email'), max_length=200)
    topics = models.CharField(_('Topics'), max_length=250)
    message = models.TextField(_('Message'))

    def __str__(self):
        return self.full_name


class Category(models.Model):
    name = models.CharField(_('Name'), max_length=100)
    slug = AutoSlugField(populate_from="name", unique=True)
    feature_image = models.ImageField(
        blank=True, null=True, upload_to='frontend/blog/categories/%Y/%m/%d/', default='default-thumb.png')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Blog (models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    feature_image = ImageField(_('Feature Image'), blank=True, null=True,
                               upload_to='frontend/blog/articles/%Y/%m/%d/', default='default-thumb.png')
    title = models.CharField(_('Title'), max_length=300)
    slug = AutoSlugField(populate_from="title", unique_with='published__month')
    published = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, related_name='category')
    content = RichTextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"slug": self.slug})


class Page(models.Model):
    title = models.CharField(_('Title'), max_length=300)
    slug = AutoSlugField(populate_from="title", unique=True)
    content = RichTextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'

frontend/forms.py
from django import forms
from frontend.models import Contact, Category, Blog, Page


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].widget.attrs.update(
            {'class': 'form-control mb-30'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-30'})
        self.fields['topics'].widget.attrs.update(
            {'class': 'form-control mb-30'})
        self.fields['message'].widget.attrs.update(
            {'class': 'form-control mb-30'})


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'
        exclude = ['author']
        widgets = {
            "category": forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['feature_image'].widget.attrs.update({'class': 'hidden'})
        self.fields['content'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['category'].widget.attrs.update(
            {'class': 'font-medium text-gray-900 dark:text-gray-300', })


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['feature_image'].widget.attrs.update({'class': 'hidden'})


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PageForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})
        self.fields['content'].widget.attrs.update(
            {'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'})

frontend/views.py
from django.shortcuts import render, redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView, DeleteView
from django.utils.translation import gettext_lazy as _
from django.core.mail import EmailMultiAlternatives
from django.contrib import messages

from frontend.models import Contact, Category, Blog, Page
from frontend.forms import ContactForm, ArticleForm, CategoryForm, PageForm


class HomeView(TemplateView):
    template_name = 'frontend/views/home.html'
    # def get_context_data(self, **kwargs):
    #     context = super(HomeView, self).get_context_data(**kwargs)
    #     context['articles'] = Blog.objects.order_by('-published')[:3]
    #     return context


class ContactView(SuccessMessageMixin, CreateView):
    model = Contact
    form_class = ContactForm
    success_message = _(
        "Your submission was successfully received, and our team will answer you as soon as possible")
    success_url = reverse_lazy("contact")
    template_name = 'frontend/views/contact.html'

    def form_valid(self, form, **kwargs):
        full_name = form.cleaned_data['full_name']
        email = form.cleaned_data['email']
        topic = form.cleaned_data['topics']
        message = form.cleaned_data['message']
        subject, from_email, to = topic, 'noreply@gisysco.com', "support@gisysco.com"
        text_content = _('New email from contact help.')
        html_content = _(
            f'Hello Team <br> <p>Mr/Ms: <strong>{full_name}</strong> need help about <strong> {topic} </strong> <br> His/Her message:<br> {message} </p> <p><a href="mailto:{email}">Reply to customer email</a></p>')
        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()
        return super().form_valid(form)

        # TODO: add notofication to the admin space  when have new contact


class DesignView(TemplateView):
    template_name = 'frontend/views/services/design.html'


class WebView(TemplateView):
    template_name = 'frontend/views/services/web_dev.html'


class MobileView(TemplateView):
    template_name = 'frontend/views/services/mobile_dev.html'


class SeoView(TemplateView):
    template_name = 'frontend/views/services/seo.html'


class MarketingView(TemplateView):
    template_name = 'frontend/views/services/marketing.html'


# Dev Tips View

class AddPostView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Blog
    template_name = 'frontend/views/blog/admin/index.html'
    success_message = _('Your post has been successfully added')
    form_class = ArticleForm
    success_url = reverse_lazy('post-admin-list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdatePostView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Blog
    form_class = ArticleForm
    template_name = 'frontend/views/blog/admin/index.html'
    success_message = _('Your post has been successfully update')
    success_url = reverse_lazy('post-admin-listt')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class DeletePostView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Blog
    template_name = 'frontend/views/blog/admin/delete.html'
    success_url = reverse_lazy('post-admin-list')
    success_message = _('Your post has been successfully deleted')


class ListPostAdminView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    model = Blog
    template_name = 'frontend/views/blog/admin/list.html'
    paginate_by = 5


class BlogView(ListView):
    model = Blog
    paginate_by = 10
    template_name = 'frontend/views/blog/blog.html'

    def get_context_data(self, **kwargs):
        kwargs['cat_list'] = Category.objects.order_by('id')
        kwargs['articles_list'] = Blog.objects.order_by('-published')[:6]

        return super(BlogView, self).get_context_data(**kwargs)


class DetailsBlogView(DetailView):
    model = Blog
    template_name = 'frontend/views/blog/details.html'

    def get_context_data(self, **kwargs):
        kwargs['cat_list'] = Category.objects.order_by('id')
        kwargs['articles_list'] = Blog.objects.order_by('-published')[:6]

        return super(DetailsBlogView, self).get_context_data(**kwargs)


class AddCategoryView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Category
    template_name = 'frontend/views/blog/admin/categories/index.html'
    success_message = _('Your category has been successfully added')
    form_class = CategoryForm
    success_url = reverse_lazy('category-add')

    def get_context_data(self, **kwargs):
        kwargs['cat_list'] = Category.objects.order_by('id')
        return super(AddCategoryView, self).get_context_data(**kwargs)


class UpdateCategoryView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Category
    template_name = 'frontend/views/blog/admin/categories/index.html'
    success_message = _('Your category has been successfully update')
    form_class = CategoryForm
    success_url = reverse_lazy('category-add')

    def get_context_data(self, **kwargs):
        kwargs['cat_list'] = Category.objects.order_by('id')
        return super(UpdateCategoryView, self).get_context_data(**kwargs)


class DeleteCategoryView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Category
    template_name = 'frontend/views/blog/admin/categories/delete.html'
    success_message = _('Your category has been successfully deleted')
    success_url = reverse_lazy('category-add')


class AddPageView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Page
    template_name = 'frontend/views/pages/admin/index.html'
    success_message = _('This page has been successfully added')
    form_class = PageForm
    success_url = reverse_lazy('page-list')


class UpdatePageView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Page
    template_name = 'frontend/views/pages/admin/index.html'
    success_message = _('This page has been successfully update')
    form_class = PageForm
    success_url = reverse_lazy('page-list')


class DeletePageView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Page
    template_name = 'frontend/views/pages/admin/delete.html'
    success_url = reverse_lazy('page-list')
    success_message = _('Your page has been successfully deleted')

    def delete(self, request, *args, **kwargs):
        messages.warning(self.request, self.success_message)
        return super(DeletePageView, self).delete(request, *args, **kwargs)


class ListPageView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    model = Page
    template_name = 'frontend/views/pages/admin/list.html'
    paginate_by = 5


class DetailPageView(SuccessMessageMixin, DetailView):
    model = Page
    template_name = 'frontend/views/pages/details.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

frontend/templates/frontend/views/contact.html
{% extends 'frontend/base.html' %}
{% load static i18n %}
{% get_current_language as language_code %}
{% block title %}
{% translate "contact" %}
{% endblock title %}

{% block content %}
<div class="breadcrumb-wrapper breadcrumb-bg-light">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div class="breadcrumb-content">
                    <h2 class="breadcrumb-title">{% translate "Hire us!" %}</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}">{% translate "Home" %}</a></li>
                            <li class="breadcrumb-item active" aria-current="page">{% translate "Contact" %}</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="mb-120 d-block"></div>
<div class="saasbox-contact-us-area">
    <div class="container">
        <div class="row g-4 justify-content-between">
            <div class="col-12 col-lg-5 col-xl-4">
                <div class="contact-side-info mb-4 mb-md-0">
                    <h1 class="mb-3">{% translate "Let's talk about all things!" %}</h1>
                    <p class="mb-4">
                        {% translate "Write to us or give us a call. We will reply to you as soon as possible. But yes, it can take up to 24 hours." %}
                    </p>
                    <div class="contact-mini-card-wrapper">
                        <div class="contact-mini-card">
                            <div class="contact-mini-card-icon"><i class="bi bi-envelope"></i></div>
                            <p>it-service@gisysco.com</p>
                        </div>
                        <div class="contact-mini-card">
                            <div class="contact-mini-card-icon"><i class="bi bi-envelope"></i></div>
                            <p>marketing@gisysco.com</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-7">
                <div class="contact-form">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-success" role="alert" id="msg">
                                <span class="font-medium">{{message}}</span>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12 col-lg-6">
                                <label class="form-label" for="id_full_name">{{form.full_name.label}}</label>
                                {{form.full_name}}
                            </div>
                            <div class="col-12 col-lg-6">
                                <label class="form-label" for="id_email">{% translate "Email Address:" %}</label>
                                {{form.email}}
                            </div>
                            <div class="col-12">
                                <label class="form-label" for="id_subject">{% translate "Topics:" %}</label>
                                {{form.topics}}
                            </div>
                            <div class="col-12">
                                <label class="form-label" for="id_message">{% translate "Message:" %}</label>
                                {{form.message}}
                            </div>
                            <div class="col-12 text-center">
                                <button class="btn btn-primary w-100" type="submit">{% translate "Send Now" %}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="mb-120 d-block"></div>
<div class="mb-120 d-block"></div>

{% endblock content %}